---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dcgm-exporter
  namespace: monitoring
spec:
  interval: 30m
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  chart:
    spec:
      chart: dcgm-exporter
      version: "3.*"
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
    tolerations:
      - operator: Exists
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
