"""
Drone Telemetry Simulator for MWC 2026 Demo
=============================================
Simulates N drones flying patrol routes in the Portland, OR metro area,
each sending 5G network-monitoring telemetry to Azure IoT Hub.

Configuration is read from a .env file (generated by 03-deploy-iot-simulation.ps1)
or from environment variables:

    IOT_HUB_NAME              – IoT Hub hostname (informational)
    DRONE_COUNT                – number of drones (default: 5)
    SEND_INTERVAL_SECONDS      – telemetry interval (default: 5)
    DRONE_<n>_CONNECTION_STRING – per-device connection string

Usage:
    pip install -r requirements.txt
    python drone-telemetry-simulator.py
"""

import json
import math
import os
import random
import signal
import sys
import threading
import time
from datetime import datetime, timezone
from pathlib import Path

from azure.iot.device import IoTHubDeviceClient, Message
from dotenv import load_dotenv

# ── Configuration ────────────────────────────────────────────────────────────

# Load .env from the same directory as this script
_script_dir = Path(__file__).resolve().parent
_env_path = _script_dir / ".env"
if _env_path.exists():
    load_dotenv(_env_path)

DRONE_COUNT = int(os.getenv("DRONE_COUNT", "5"))
SEND_INTERVAL = float(os.getenv("SEND_INTERVAL_SECONDS", "5"))

# Barcelona, Spain — Fira Gran Via / MWC venue area
BCN_CENTER_LAT = 41.3574
BCN_CENTER_LON = 2.1286
BCN_RADIUS_DEG = 0.04  # ~4.5 km

# Shutdown event
_shutdown = threading.Event()


# ── Drone state ──────────────────────────────────────────────────────────────

class Drone:
    """Tracks the simulated state of a single drone."""

    STATUSES = ["patrolling", "hovering", "returning", "charging"]

    def __init__(self, drone_id: int, connection_string: str):
        self.drone_id = f"drone-{drone_id}"
        self.connection_string = connection_string
        self.client: IoTHubDeviceClient | None = None

        # Initial position: spread drones evenly around the center
        angle = 2 * math.pi * (drone_id - 1) / max(DRONE_COUNT, 1)
        self.lat = BCN_CENTER_LAT + BCN_RADIUS_DEG * 0.6 * math.cos(angle)
        self.lon = BCN_CENTER_LON + BCN_RADIUS_DEG * 0.6 * math.sin(angle)
        self.altitude_m = random.uniform(50, 150)  # metres AGL
        self.heading_deg = random.uniform(0, 360)

        # Telemetry state
        self.battery_pct = random.uniform(60, 100)
        self.status = "patrolling"
        self.speed_mps = random.uniform(5, 15)  # m/s

    def connect(self):
        """Create and connect the IoT Hub device client."""
        self.client = IoTHubDeviceClient.create_from_connection_string(
            self.connection_string
        )
        self.client.connect()
        print(f"  [{self.drone_id}] Connected to IoT Hub")

    def disconnect(self):
        if self.client:
            try:
                self.client.shutdown()
            except Exception:
                pass

    # ── Physics-lite step ────────────────────────────────────────────────────

    def step(self):
        """Advance the drone state by one tick."""
        # Drift position slightly
        self.lat += random.gauss(0, 0.0005)
        self.lon += random.gauss(0, 0.0005)
        self.altitude_m = max(20, self.altitude_m + random.gauss(0, 2))
        self.heading_deg = (self.heading_deg + random.gauss(0, 10)) % 360
        self.speed_mps = max(0, self.speed_mps + random.gauss(0, 1))

        # Battery drain
        self.battery_pct = max(0, self.battery_pct - random.uniform(0.02, 0.1))
        if self.battery_pct < 15:
            self.status = "returning"
        elif self.battery_pct < 5:
            self.status = "charging"
            self.speed_mps = 0
        else:
            self.status = random.choices(
                ["patrolling", "hovering"],
                weights=[0.85, 0.15],
            )[0]

    # ── Telemetry generation ─────────────────────────────────────────────────

    def build_telemetry(self) -> dict:
        """Build a telemetry payload with MWC-relevant 5G network metrics."""
        self.step()

        return {
            "drone_id": self.drone_id,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            # ── Location ──
            "location": {
                "latitude": round(self.lat, 6),
                "longitude": round(self.lon, 6),
                "altitude_m": round(self.altitude_m, 1),
                "heading_deg": round(self.heading_deg, 1),
                "speed_mps": round(self.speed_mps, 1),
            },
            # ── 5G / network monitoring ──
            "network": {
                "signal_rsrp_dbm": random.randint(-120, -60),     # Reference Signal Received Power
                "signal_rsrq_db": round(random.uniform(-20, -3), 1),  # Ref Signal Received Quality
                "signal_sinr_db": round(random.uniform(-5, 30), 1),   # Signal-to-Interference+Noise
                "cell_id": random.randint(100000, 999999),
                "band": random.choice(["n77", "n78", "n79", "n260", "n261"]),  # 5G NR bands
                "downlink_mbps": round(random.uniform(50, 1200), 1),
                "uplink_mbps": round(random.uniform(10, 200), 1),
                "latency_ms": round(random.uniform(1, 25), 1),
                "packet_loss_pct": round(random.uniform(0, 2), 3),
                "connected": random.choices([True, False], weights=[0.95, 0.05])[0],
            },
            # ── Drone health ──
            "battery_pct": round(self.battery_pct, 1),
            "status": self.status,
            # ── Environmental ──
            "environment": {
                "temperature_c": round(random.uniform(5, 35), 1),
                "wind_speed_mps": round(random.uniform(0, 15), 1),
                "humidity_pct": round(random.uniform(30, 90), 1),
            },
        }

    def send_telemetry(self):
        """Build and send one telemetry message."""
        payload = self.build_telemetry()
        msg = Message(json.dumps(payload))
        msg.content_type = "application/json"
        msg.content_encoding = "utf-8"
        msg.custom_properties["drone_id"] = self.drone_id
        self.client.send_message(msg)
        return payload


# ── Worker thread ────────────────────────────────────────────────────────────

def drone_worker(drone: Drone):
    """Run a single drone's telemetry loop in its own thread."""
    try:
        drone.connect()
        while not _shutdown.is_set():
            try:
                payload = drone.send_telemetry()
                net = payload["network"]
                print(
                    f"  [{drone.drone_id}] "
                    f"lat={payload['location']['latitude']:.4f} "
                    f"lon={payload['location']['longitude']:.4f} "
                    f"rsrp={net['signal_rsrp_dbm']}dBm "
                    f"dl={net['downlink_mbps']}Mbps "
                    f"lat_ms={net['latency_ms']}ms "
                    f"bat={payload['battery_pct']:.0f}% "
                    f"[{payload['status']}]"
                )
            except Exception as e:
                print(f"  [{drone.drone_id}] Send error: {e}", file=sys.stderr)
            _shutdown.wait(SEND_INTERVAL)
    except Exception as e:
        print(f"  [{drone.drone_id}] Fatal error: {e}", file=sys.stderr)
    finally:
        drone.disconnect()


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("  Drone Telemetry Simulator — MWC 2026 Demo")
    print(f"  Drones: {DRONE_COUNT}   Interval: {SEND_INTERVAL}s")
    print("=" * 60)
    print()

    # Build drone list
    drones: list[Drone] = []
    for i in range(1, DRONE_COUNT + 1):
        conn_str = os.getenv(f"DRONE_{i}_CONNECTION_STRING", "")
        if not conn_str:
            print(f"  ⚠️  DRONE_{i}_CONNECTION_STRING not set — skipping drone-{i}")
            continue
        drones.append(Drone(drone_id=i, connection_string=conn_str))

    if not drones:
        print("No drones configured. Set DRONE_<n>_CONNECTION_STRING env vars or run 03-deploy-iot-simulation.ps1.")
        sys.exit(1)

    print(f"\nStarting {len(drones)} drone(s)... Press Ctrl+C to stop.\n")

    # Graceful shutdown
    def _signal_handler(sig, frame):
        print("\n\n🛑 Shutting down...")
        _shutdown.set()

    signal.signal(signal.SIGINT, _signal_handler)
    signal.signal(signal.SIGTERM, _signal_handler)

    # Launch threads
    threads: list[threading.Thread] = []
    for drone in drones:
        t = threading.Thread(target=drone_worker, args=(drone,), daemon=True)
        t.start()
        threads.append(t)
        time.sleep(0.2)  # Stagger connections slightly

    # Wait for shutdown
    for t in threads:
        t.join()

    print("All drones stopped. Goodbye.")


if __name__ == "__main__":
    main()