"""
Drone Telemetry Simulator for MWC 2026 Demo
=============================================
Simulates N drones flying waypoint-based patrol routes around Barcelona,
each sending 5G network-monitoring telemetry to Azure IoT Hub.

Drones:
  - Follow purposeful patrol routes between Barcelona landmarks
  - Return to base (Fira Gran Via) when battery drops below threshold
  - Recharge at base, then launch again with fresh battery & new route

Configuration is read from a .env file (generated by 03-deploy-iot-simulation.ps1)
or from environment variables:

    IOT_HUB_NAME              – IoT Hub hostname (informational)
    DRONE_COUNT                – number of drones (default: 5)
    SEND_INTERVAL_SECONDS      – telemetry interval (default: 5)
    DRONE_<n>_CONNECTION_STRING – per-device connection string

Usage:
    pip install -r requirements.txt
    python drone-telemetry-simulator.py
"""

import json
import math
import os
import random
import signal
import sys
import threading
import time
from datetime import datetime, timezone
from pathlib import Path

from azure.iot.device import IoTHubDeviceClient, Message
from dotenv import load_dotenv

try:
    import paho.mqtt.client as mqtt
    PAHO_AVAILABLE = True
except ImportError:
    PAHO_AVAILABLE = False

DATA_MODE = os.getenv("DATA_MODE", "cloud")
MQTT_BROKER_HOST = os.getenv("MQTT_BROKER_HOST", "aio-broker-insecure.azure-iot-operations.svc")
MQTT_BROKER_PORT = int(os.getenv("MQTT_BROKER_PORT", "1883"))
MQTT_TOPIC_PREFIX = os.getenv("MQTT_TOPIC_PREFIX", "drone/telemetry")

# ── Configuration ────────────────────────────────────────────────────────────

# Load .env from the same directory as this script
_script_dir = Path(__file__).resolve().parent
_env_path = _script_dir / ".env"
if _env_path.exists():
    load_dotenv(_env_path)

DRONE_COUNT = int(os.getenv("DRONE_COUNT", "5"))
SEND_INTERVAL = float(os.getenv("SEND_INTERVAL_SECONDS", "5"))

# Barcelona, Spain — Fira Gran Via / MWC venue area
BCN_CENTER_LAT = 41.3574
BCN_CENTER_LON = 2.1286

# Base / home pad — MWC venue
BASE_LAT, BASE_LON = 41.3545, 2.1279

# Battery thresholds
BATTERY_RETURN = 18        # % — start flying home
BATTERY_CRITICAL = 5       # % — forced landing
BATTERY_LAUNCH = 92        # % — charged enough to relaunch
CHARGE_RATE = 0.30         # % per tick while charging
DRAIN_RATE_MIN = 0.020     # % per tick while flying
DRAIN_RATE_MAX = 0.055     # % per tick while flying
LAUNCH_CLIMB_TICKS = 6     # ticks to reach patrol altitude
LANDING_TICKS = 5          # ticks to descend at base

# Patrol waypoints — Barcelona landmarks spread over ~8 km
PATROL_WAYPOINTS = [
    (41.3700, 2.1100),  # Montjuic hilltop
    (41.3650, 2.1500),  # Eixample / Sagrada Familia area
    (41.3870, 2.1200),  # Placa Catalunya
    (41.3520, 2.1680),  # Port Olimpic
    (41.3780, 2.1450),  # Gracia
    (41.3460, 2.1350),  # Zona Franca industrial
    (41.3620, 2.1050),  # Sants station
    (41.3900, 2.1650),  # Diagonal Mar
    (41.3740, 2.0980),  # Pedralbes
    (41.3580, 2.1800),  # Poblenou
    (41.3830, 2.1100),  # Les Corts / Camp Nou
    (41.3480, 2.1500),  # Parallel / Poble Sec
]

# Shutdown event
_shutdown = threading.Event()


# ── Drone state ──────────────────────────────────────────────────────────────

class Drone:
    """Tracks the simulated state of a single drone with waypoint-based patrol,
    return-to-base on low battery, and automatic relaunch after charging."""

    STATUSES = ["launching", "patrolling", "hovering", "returning", "landing", "charging"]

    def __init__(self, drone_id: int, connection_string: str):
        self.drone_id = f"drone-{drone_id}"
        self.drone_idx = drone_id
        self.connection_string = connection_string
        self.client: IoTHubDeviceClient | None = None
        self._init_flight()

    def _init_flight(self):
        """(Re)initialise flight state for a fresh sortie."""
        # Start at base with slight spread so drones don't stack
        angle = 2 * math.pi * (self.drone_idx - 1) / max(DRONE_COUNT, 1)
        self.lat = BASE_LAT + 0.0004 * math.cos(angle)
        self.lon = BASE_LON + 0.0004 * math.sin(angle)
        self.altitude_m = 0.0
        self.heading_deg = random.uniform(0, 360)

        self.battery_pct = random.uniform(88, 100)
        self.status = "launching"
        self.speed_mps = 0.0
        self._lifecycle_tick = 0

        # Pick 4-6 random patrol waypoints for this sortie
        self.waypoints = random.sample(
            PATROL_WAYPOINTS, random.randint(4, min(6, len(PATROL_WAYPOINTS)))
        )
        self.wp_idx = 0
        print(f"  [{self.drone_id}] New sortie — {len(self.waypoints)} waypoints, battery {self.battery_pct:.0f}%")

    def connect(self):
        """Create and connect the IoT Hub device client."""
        self.client = IoTHubDeviceClient.create_from_connection_string(
            self.connection_string
        )
        self.client.connect()
        print(f"  [{self.drone_id}] Connected to IoT Hub")

    def disconnect(self):
        if self.client:
            try:
                self.client.shutdown()
            except Exception:
                pass

    # ── Movement helpers ─────────────────────────────────────────────────────

    def _move_toward(self, target_lat: float, target_lon: float) -> bool:
        """Fly toward *target* at current speed. Returns True when arrived."""
        dlat = target_lat - self.lat
        dlon = target_lon - self.lon
        dist = math.sqrt(dlat ** 2 + dlon ** 2)

        if dist < 0.0004:  # ~40 m — close enough
            return True

        # degrees per tick  (speed_mps * interval_s / ~111 000 m/deg)
        step = min(self.speed_mps * SEND_INTERVAL / 111_000, dist)
        self.lat += dlat / dist * step
        self.lon += dlon / dist * step
        self.heading_deg = math.degrees(math.atan2(dlon, dlat)) % 360

        # Slight realism wobble
        self.lat += random.gauss(0, 0.00003)
        self.lon += random.gauss(0, 0.00003)
        return False

    # ── Lifecycle steps ──────────────────────────────────────────────────────

    def step(self):
        """Advance the drone state by one tick."""
        self._lifecycle_tick += 1

        if self.status == "launching":
            self._step_launching()
        elif self.status in ("patrolling", "hovering"):
            self._step_patrolling()
        elif self.status == "returning":
            self._step_returning()
        elif self.status == "landing":
            self._step_landing()
        elif self.status == "charging":
            self._step_charging()

    def _step_launching(self):
        self.speed_mps = random.uniform(3, 6)
        self.altitude_m = min(120, self.altitude_m + random.uniform(10, 20))
        self.battery_pct -= random.uniform(DRAIN_RATE_MIN, DRAIN_RATE_MAX)
        wp = self.waypoints[0]
        self._move_toward(wp[0], wp[1])
        if self._lifecycle_tick >= LAUNCH_CLIMB_TICKS:
            self.status = "patrolling"
            self.speed_mps = random.uniform(8, 14)
            self._lifecycle_tick = 0
            print(f"  [{self.drone_id}] Launched — heading to waypoint 1")

    def _step_patrolling(self):
        wp = self.waypoints[self.wp_idx]
        arrived = self._move_toward(wp[0], wp[1])

        self.speed_mps = max(4, min(18, self.speed_mps + random.gauss(0, 0.8)))
        self.altitude_m = max(40, min(180, self.altitude_m + random.gauss(0, 1.5)))
        self.battery_pct -= random.uniform(DRAIN_RATE_MIN, DRAIN_RATE_MAX)

        if arrived:
            self.wp_idx = (self.wp_idx + 1) % len(self.waypoints)
            if random.random() < 0.25:
                self.status = "hovering"
                self.speed_mps = random.uniform(0, 2)
                self._lifecycle_tick = 0
            else:
                print(f"  [{self.drone_id}] Reached waypoint — next #{self.wp_idx + 1}")

        if self.battery_pct <= BATTERY_RETURN:
            self.status = "returning"
            self._lifecycle_tick = 0
            self.speed_mps = random.uniform(12, 16)
            print(f"  [{self.drone_id}] LOW BATTERY ({self.battery_pct:.0f}%) — returning to base")

        if self.status == "hovering" and self._lifecycle_tick >= random.randint(3, 8):
            self.status = "patrolling"
            self.speed_mps = random.uniform(8, 14)
            self._lifecycle_tick = 0

    def _step_returning(self):
        arrived = self._move_toward(BASE_LAT, BASE_LON)
        self.speed_mps = max(6, min(18, self.speed_mps + random.gauss(0, 0.5)))
        self.altitude_m = max(30, min(180, self.altitude_m + random.gauss(0, 1)))
        self.battery_pct = max(0, self.battery_pct - random.uniform(DRAIN_RATE_MIN, DRAIN_RATE_MAX))

        if arrived or self.battery_pct <= BATTERY_CRITICAL:
            self.status = "landing"
            self._lifecycle_tick = 0
            print(f"  [{self.drone_id}] At base — landing")

    def _step_landing(self):
        self.speed_mps = max(0, self.speed_mps - random.uniform(0.5, 1.5))
        self.altitude_m = max(0, self.altitude_m - random.uniform(12, 25))
        self.battery_pct = max(0, self.battery_pct - random.uniform(0.01, 0.02))
        self._move_toward(BASE_LAT, BASE_LON)

        if self._lifecycle_tick >= LANDING_TICKS or self.altitude_m <= 0:
            self.altitude_m = 0
            self.speed_mps = 0
            self.status = "charging"
            self._lifecycle_tick = 0
            print(f"  [{self.drone_id}] Landed — charging")

    def _step_charging(self):
        self.speed_mps = 0
        self.altitude_m = 0
        self.battery_pct = min(100, self.battery_pct + CHARGE_RATE)

        if self.battery_pct >= BATTERY_LAUNCH:
            print(f"  [{self.drone_id}] Charged to {self.battery_pct:.0f}% — relaunching!")
            self._init_flight()  # fresh sortie, new waypoints

    # ── Telemetry generation ─────────────────────────────────────────────────

    def build_telemetry(self) -> dict:
        """Build a telemetry payload with MWC-relevant 5G network metrics."""
        self.step()

        return {
            "drone_id": self.drone_id,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            # ── Location ──
            "location": {
                "latitude": round(self.lat, 6),
                "longitude": round(self.lon, 6),
                "altitude_m": round(self.altitude_m, 1),
                "heading_deg": round(self.heading_deg, 1),
                "speed_mps": round(self.speed_mps, 1),
            },
            # ── 5G / network monitoring ──
            "network": {
                "signal_rsrp_dbm": random.randint(-120, -60),     # Reference Signal Received Power
                "signal_rsrq_db": round(random.uniform(-20, -3), 1),  # Ref Signal Received Quality
                "signal_sinr_db": round(random.uniform(-5, 30), 1),   # Signal-to-Interference+Noise
                "cell_id": random.randint(100000, 999999),
                "band": random.choice(["n77", "n78", "n79", "n260", "n261"]),  # 5G NR bands
                "downlink_mbps": round(random.uniform(50, 1200), 1),
                "uplink_mbps": round(random.uniform(10, 200), 1),
                "latency_ms": round(random.uniform(1, 25), 1),
                "packet_loss_pct": round(random.uniform(0, 2), 3),
                "connected": random.choices([True, False], weights=[0.95, 0.05])[0],
            },
            # ── Drone health ──
            "battery_pct": round(self.battery_pct, 1),
            "status": self.status,
            # ── Environmental ──
            "environment": {
                "temperature_c": round(random.uniform(5, 35), 1),
                "wind_speed_mps": round(random.uniform(0, 15), 1),
                "humidity_pct": round(random.uniform(30, 90), 1),
            },
        }

    def send_telemetry(self):
        """Build and send one telemetry message."""
        payload = self.build_telemetry()
        msg = Message(json.dumps(payload))
        msg.content_type = "application/json"
        msg.content_encoding = "utf-8"
        msg.custom_properties["drone_id"] = self.drone_id
        self.client.send_message(msg)
        return payload


# ── Worker thread ────────────────────────────────────────────────────────────

def drone_worker(drone: Drone):
    """Run a single drone's telemetry loop in its own thread."""
    try:
        drone.connect()
        while not _shutdown.is_set():
            try:
                payload = drone.send_telemetry()
                net = payload["network"]
                print(
                    f"  [{drone.drone_id}] "
                    f"lat={payload['location']['latitude']:.4f} "
                    f"lon={payload['location']['longitude']:.4f} "
                    f"rsrp={net['signal_rsrp_dbm']}dBm "
                    f"dl={net['downlink_mbps']}Mbps "
                    f"lat_ms={net['latency_ms']}ms "
                    f"bat={payload['battery_pct']:.0f}% "
                    f"[{payload['status']}]"
                )
            except Exception as e:
                print(f"  [{drone.drone_id}] Send error: {e}", file=sys.stderr)
            _shutdown.wait(SEND_INTERVAL)
    except Exception as e:
        print(f"  [{drone.drone_id}] Fatal error: {e}", file=sys.stderr)
    finally:
        drone.disconnect()


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("  Drone Telemetry Simulator — MWC 2026 Demo")
    print(f"  Drones: {DRONE_COUNT}   Interval: {SEND_INTERVAL}s   Return at: {BATTERY_RETURN}% battery")
    print("=" * 60)
    print()

    # Build drone list
    drones: list[Drone] = []
    for i in range(1, DRONE_COUNT + 1):
        conn_str = os.getenv(f"DRONE_{i}_CONNECTION_STRING", "")
        if not conn_str:
            print(f"  ⚠️  DRONE_{i}_CONNECTION_STRING not set — skipping drone-{i}")
            continue
        drones.append(Drone(drone_id=i, connection_string=conn_str))

    if not drones:
        print("No drones configured. Set DRONE_<n>_CONNECTION_STRING env vars or run 03-deploy-iot-simulation.ps1.")
        sys.exit(1)

    print(f"\nStarting {len(drones)} drone(s)... Press Ctrl+C to stop.\n")

    # Graceful shutdown
    def _signal_handler(sig, frame):
        print("\n\n🛑 Shutting down...")
        _shutdown.set()

    signal.signal(signal.SIGINT, _signal_handler)
    signal.signal(signal.SIGTERM, _signal_handler)

    # Launch threads
    threads: list[threading.Thread] = []
    for drone in drones:
        t = threading.Thread(target=drone_worker, args=(drone,), daemon=True)
        t.start()
        threads.append(t)
        time.sleep(0.2)  # Stagger connections slightly

    # Wait for shutdown
    for t in threads:
        t.join()

    print("All drones stopped. Goodbye.")


if __name__ == "__main__":
    main()